services:
    twig.extension.array:
      class: Twig_Extensions_Extension_Array
      tags:
        - { name: twig.extension }

    twig.extension.text:
      class: Twig_Extensions_Extension_Text
      tags:
        - { name: twig.extension }

    twigdate.listener_request:
      class: ST\CoreBundle\Service\TwigDateRequestListener
      arguments: ["@twig"]
      tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }