st_user.remove_profile_picture:
    path: /profile/remove-profile-picture/{id}
    defaults: { _controller: STUserBundle:User:removeProfilePicture }
    requirements:
        id: \d+

st_user.users:
    path: /utilisateurs
    defaults: { _controller: STUserBundle:User:index }

st_user.users.add_user:
    path: /utilisateurs/ajouter
    defaults: { _controller: STUserBundle:User:add }

st_user.users.edit_user:
    path: /utilisateurs/{id}/modifier
    defaults: { _controller: STUserBundle:User:edit }
    requirements:
        id: \d+

st_user.users.delete_user:
    path: /utilisateurs/{id}/supprimer
    defaults: { _controller: STUserBundle:User:delete }
    requirements:
        id: \d+

st_user.users.user_delete_account:
    path: /profil/supprimer-mon-compte
    defaults: { _controller: STUserBundle:User:deleteMyAccount }

st_user.users.view_profile:
    path: /profil/{id}
    defaults: { _controller: STUserBundle:User:view }
    requirements:
        id: \d+
