services:
    st_user.form.registration:
        class: ST\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: st_user_registration }

    st_user.registration_listener:
        class: ST\UserBundle\EventListener\RegistrationListener
        arguments: ["@router", "@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_subscriber }

    st_user.form.profile:
        class: ST\UserBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: st_user_profile }