st_snowtricks.homepage:
    path:     /
    defaults: { _controller: STSnowTricksBundle:Family:index }

st_snowtricks.family_view:
    path: /groupes/{id}/{slug}
    defaults: { _controller: STSnowTricksBundle:Family:view }
    requirements:
      id: \d+

st_snowtricks.family_add:
    path: /groupes/ajouter
    defaults: { _controller: STSnowTricksBundle:Family:add }

st_snowtricks.family_edit:
    path: /groupes/modifier/{id}/{slug}
    defaults: { _controller: STSnowTricksBundle:Family:edit }
    requirements:
      id: \d+

st_snowtricks.family_delete:
    path: /groupes/supprimer/{id}/{slug}
    defaults: { _controller: STSnowTricksBundle:Family:delete }
    requirements:
      id: \d+

st_snowtricks.family_list:
    path: /groupes
    defaults: { _controller: STSnowTricksBundle:Family:list }

st_snowtricks.trick_view:
    path: /figure/{id}/{slug}
    defaults: { _controller: STSnowTricksBundle:Trick:view }
    requirements:
      id: \d+

st_snowtricks.trick_add:
    path: /figures/ajouter
    defaults: { _controller: STSnowTricksBundle:Trick:add }

st_snowtricks.trick_add_in:
    path: /groupes/{family}/figures/ajouter
    defaults: { _controller: STSnowTricksBundle:Trick:add }

st_snowtricks.trick_edit:
    path: /figures/modifier/{id}/{slug}
    defaults: { _controller: STSnowTricksBundle:Trick:edit }
    requirements:
      id: \d+

st_snowtricks.trick_delete:
    path: /figures/supprimer/{id}/{slug}
    defaults: { _controller: STSnowTricksBundle:Trick:delete }
    requirements:
      id: \d+

st_snowtricks.trick_remove_picture:
    path: /figures/{trick_id}/remove-picture/{picture_id}
    defaults: { _controller: STSnowTricksBundle:Trick:removePictureFromTrick }
    requirements:
        trick_id: \d+
        picture_id: \d+

st_snowtricks.trick_comments:
    path: /figures/{trick}/comments/{page}
    defaults: 
        _controller: STSnowTricksBundle:Comment:list
        page: 0
    requirements:
        trick: \d+
        page: \d+

st_snowtricks.trick_comments.add:
    path: /figures/{trick}/comments/add
    defaults: { _controller: STSnowTricksBundle:Comment:add }
    requirements:
        trick: \d+

st_snowtricks.trick_comments.edit:
    path: /comment/edit/{id}
    defaults: { _controller: STSnowTricksBundle:Comment:edit }
    requirements:
        id: \d+

st_snowtricks.trick_comments.delete:
    path: /comment/delete/{id}
    defaults: { _controller: STSnowTricksBundle:Comment:delete }
    requirements:
        id: \d+