st_snowtricks:
    resource: "@STSnowTricksBundle/Resources/config/routing.yml"
    prefix:   /

st_user:
    resource: "@STUserBundle/Resources/config/routing.yml"
    prefix: /users

fos_user_profile_show:
    path:  /profil
    defaults: { _controller: FOSUserBundle:Profile:show }

fos_user_profile_edit:
    path: /profil/modifier-profil
    defaults: { _controller: FOSUserBundle:Profile:edit }

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /inscription

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /modifier-mot-de-passe

fos_user_security_login:
    path: /connexion
    defaults: { _controller: FOSUserBundle:Security:login }
    requirements:
        _method: GET|POST

fos_user_security_check:
    path: /login_check
    defaults: { _controller: FOSUserBundle:Security:check }

fos_user_security_logout:
    path: /logout
    defaults: { _controller: FOSUserBundle:Security:logout }
    requirements:
        _method: GET|POST

