<?php

namespace ST\SnowTricksBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
use ST\SnowTricksBundle\Entity\Trick;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
	public function getPaginatedComments($page = 0, $maxResults = 10, Trick $entity = null)
	{
		$query = $this
					->createQueryBuilder('c')
		            ->where('c.trick = :trick')
		            ->setParameter('trick', $entity->getId())
		            ->setFirstResult($page * $maxResults)
		            ->setMaxResults($maxResults)
		            ->orderBy('c.id', 'desc');

        $result = new Paginator($query);

        return $result;
	}
}
