<?php

namespace ST\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByGroup($groupName)
    {
    	$qb = $this->createQueryBuilder('u');
        return 
	        $qb
	        	->join('u.groups', 'g')
	        	->where('g.name = :groupName')
	        	->setParameter('groupName', $groupName)
	        	->getQuery()
	        	->getResult();
    }
}
